apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z boutique-postgres 5432; do echo waiting for postgres; sleep 2; done']
      containers:
        - name: auth
          image: 141701955627.dkr.ecr.us-east-1.amazonaws.com/auth:9e628e554d79f1435ec1f23b32392c2bfe45e043
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3002"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: AUTH_DB_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20

--- 

apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: boutique
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
